### ISSUE TITLE
Does not respect .eslintrc files in directory tree

### ISSUE THREAD

**Issue by mtscout6** [MoOx/eslint-loader#21] opened 2015-03-16 19:01 UTC
I have a large app that will be transitioning to es6 over the next few months. Which means I need a different `.eslintrc` configuration for the new es6 javascript and the old es5 scripts. I also have a test directory which has a different configuration. Using eslint from the command line the proper configurations are derived according to the directory structure.

Here is a mockup directory structure:

```
|--- src
    |--- content
        |--- scripts
            |--- es6
                |--- .eslintrc
                |--- **/*.js               <-- (es6 javascript)
            |--- test
                |--- .eslintrc
                |--- **/*Spec.js       <-- (javascript unit tests)
            |--- **/*.js                   <-- (es5 javascript)
        |--- styles
            |--- **/*.less
    |--- *.cs (C# files)
|--- .eslintrc
```

What seems to be happening is that the `.eslintrc` file at the root of my repo is the only one getting picked up. Thoughts?

**Comment by mtscout6** [comment] 2015-03-16 19:18
Using this might help: https://github.com/eslint/eslint/blob/v0.17.0/lib/config.js#L332

**Comment by MoOx** [comment] 2015-03-17 06:26
The problem is that webpack loaders do not give the filename but only send the input to process.
So I can't handle this case because I am using eslint CLIEngine#executeOnText().

In order to fix that we need first the filename in the loader (poke @sokra) so we can pass to eslint in order to get proper eslintrc file.

**Comment by sokra** [comment] 2015-03-17 06:43
You have access to the filename in the loader function via `this.resourcePath`. The jshint-loader also uses .jshintrc

**Comment by MoOx** [comment] 2015-03-17 09:23
Oh good to know. Thanks @sokra.
I will update the loader accordingly.

**Comment by mtscout6** [comment] 2015-03-18 21:10
When you do this can you also respect the `.eslintignore` file? Or would you prefer a separate issue for that?

**Comment by MoOx** [comment] 2015-03-19 05:56
Yes please, a separate issue. Or a separate PR ;)

**Comment by MoOx** [comment] 2015-03-27 08:02
@mtscout6 I investigated on this issue.

For now this cannot be done properly since method that use text for processing doesn't accept filepath or something that will allow us to adjust the config (`executeOnText()`/`processText()` just call `getConfig()` without arguments, and I cannot change that).
I cannot use something at a lower level (eg: `verify()`) cause in this case, I can't access private `loadPlugins()` method (which is called by other higher level method) and so plugins will not be loaded.
I can use `processOnFile()` but that will use a fs read which is stupid because it has already been done.
We need to open an issue on eslint to 
- add a parameter to text methods to receive a filename to pass to `getConfig()`
OR
- make public `loadPlugins()` methods and other methods that  might be required to use in order to get a full linting.

I hope I am clear on this.

poke @nzakas

**Comment by tomchentw** [comment] 2015-05-12 11:21
Experienced the same issue today, thanks for investigating.
@MoOx ++

**Comment by nzakas** [comment] 2015-05-12 16:26
@MoOx please file an issue if you have a request

**Comment by DanPantry** [comment] 2015-05-15 12:08
+1 seems that `eslint-loader` is still not respecting `.eslintrc`

**Comment by MoOx** [comment] 2015-05-15 12:31
It depends on your setup. I sucessfuly use .eslintrc on a lot of project using this loader.
Like Nicholas said, someone can open an issue on eslint repo, I think I gave enough information to help.

**Comment by MoOx** [comment] 2015-06-04 05:56
Closed by 1bf9bf9b0731bc6dcd40adccd9306340fd6a67fb

**Closed by MoOx** 2015-06-04 05:56 UTC

**Comment by tomchentw** [comment] 2015-06-09 10:21
This is awesome! Thanks @MoOx !!

**Comment by MoOx** [comment] 2015-06-09 10:24
Do not thank me. Thanks @mgtitimoli
But... #44
