### ISSUE TITLE
eslint-loader in watch mode only works when a new line is added

### ISSUE THREAD

**Issue by kiranps** [MoOx/eslint-loader#78] opened 2016-02-04 06:45 UTC

**Comment by kiranps** [comment] 2016-02-04 06:49
i'm running eslint along with webpack

    let a = 0

for above line esling gives `error  Missing semicolon`

if i fixed it by adding ;

    let a = 0;

watch mode does not reloads. if add another line

    let a = 0;
    let b = 0;

eslint reloads

**Comment by MoOx** [comment] 2016-02-05 07:14
Maybe it's an webpack caching issue.
What other loaders are you using?
Can you try commenting that line https://github.com/MoOx/eslint-loader/blob/master/index.js#L111?

**Comment by kiranps** [comment] 2016-02-06 06:42
@MoOx commenting the line didn't worked

I also use babel loader, if i remove babel loader from webpack.config.js watch mode works whenever i make changes in a single line.

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: './src/app.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'bundle.js'
  },
  module: {
    preLoaders: [
      {test: /\.js$/, loader: "eslint-loader", exclude: /node_modules/}
    ],
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        query: {
          presets: ['es2015']
        }
      }
    ]
  },
  stats: {
    colors: true
  },
  watch: true
};
```

**Comment by kiranps** [comment] 2016-02-06 07:43
It looks like issue is with the webpack. with webpack-dev-server its working fine

railsed an issue in webpack

[https://github.com/webpack/webpack/issues/2009](url)

**Comment by MoOx** [comment] 2016-02-13 09:18
Try using eslint as a loader, not a preloader, after babel (so before on runtime).

**Comment by tvervest** [comment] 2016-03-11 15:00
This issue might be related to #69.

My setup is identical to to the module section in [kiranps' comment on Feb 6](https://github.com/MoOx/eslint-loader/issues/78#issuecomment-180706542). Removing eslint or commenting out [line 71](https://github.com/MoOx/eslint-loader/blob/master/index.js#L71 fixes the issue, but (obviously) disables linting. I also noticed that reloading works correctly when the build runs successfully on the initial run.

I hope we can fix this! I use this plugin on another project and it's very convenient, would be nice to be able to not have to constantly restart webpack if I was lazy the day before ;p

**Comment by andreypopp** [comment] 2016-06-07 20:26
The issue is with how webpack reports errors, see [this line](https://github.com/webpack/webpack/blob/master/bin/webpack.js#L259). So the absence/presence of a semicolon doesn't really make a difference for webpack as babel loader generates identical code.

btw. I created a plugin for webpack called [prefetch-context-webpack-plugin](https://github.com/andreypopp/prefetch-context-webpack-plugin) which works very well with `eslint-loader`:

```
import PrefetchContext from 'prefetch-context-webpack-plugin'

module.exports = {

  ...

  plugins: [
    new PrefetchContext({
      context: './src',
      loader: 'eslint-loader',
    })
  ]
}
```

All it does is it prefetches every file under a directory and processes it through a loader (`eslint-loader` in this example). This matches what `eslint` does, processes every file in a directory and not only those which are in the bundle. Still it reuses webpack caches and so it is fast.

I also fixed error reporting in the plugin, see [here](https://github.com/andreypopp/prefetch-context-webpack-plugin/blob/master/src/index.js#L44-L50) though it's a little bit hacky and I'd prefer to raise an issue in webpack regarding that use case.

**Comment by thetrevdev** [comment] 2016-09-25 05:13
See https://github.com/webpack/webpack/issues/2538

**Comment by rickyk586** [comment] 2016-11-15 09:52
This solution worked for me: https://github.com/webpack/webpack/issues/675#issuecomment-224991459

**Comment by sth** [comment] 2017-01-28 15:25
As a work around until webpack fixes its error reporting I [added a plugin][1] to my project that makes sure the babel output changes even for trivial changes in the input. This forces webpack to reprocesses the changed file which displays the updated eslint messages.

 [1]: https://github.com/sth/babel-plugin-add-filehash

**Comment by rafalp** [comment] 2017-10-26 18:48
Note that this issue has been fixed as of Webpack 3

**Comment by MoOx** [comment] 2017-10-26 19:17
Good to know!

**Closed by MoOx** 2017-10-26 19:17 UTC
