### ISSUE TITLE
ecmaFeatures error with Webpack 2 and Eslint 2

### ISSUE THREAD

**Issue by dtothefp** [MoOx/eslint-loader#80] opened 2016-02-13 00:31 UTC
This is probably not the correct place to be placing this issue but I don't know where to start because there are so many tools involved. Upon updating to Eslint 2 and Webpack 2 I get an error in `espree` shown below. With Webpack 1 I don't get this error, and with Webpack `2.0.7.-beta` and Eslint `1.x` I don't get the error as well. If you have any ideas and cold point me in the right direction I'd appreciate it. 

```json
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "env": {
    "browser": true,
    "node": true
  },
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module",
    "ecmaFeatures": {
      "arrowFunctions": true,
      "blockBindings": true,
      "experimentalObjectRestSpread": true,
      "generators": true,
      "jsx": true,
      "module": true,
      "modules": true,
      "restParams": true,
      "spread": true,
      "jsx": true
    }
  }
}
``` 

```
ERROR in ./src/js/index.js
Module parse failed: /Users/davidfox-powell/dev/frontend-boilerplate/node_modules/babel-loader/index.js?{"presets":["react","es2015","stage-0"],"plugins":["transform-runtime","transform-decorators-legacy","typecheck",["react-transform",{"transforms":[{"transform":"react-transform-hmr","imports":["react"],"locals":["module"]},{"transform":"react-transform-catch-errors","imports":["react","redbox-react"]}]}]]}!/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/eslint-loader/index.js!/Users/davidfox-powell/dev/frontend-boilerplate/src/js/index.js 
Cannot read property 'ecmaFeatures' of undefined
You may need an appropriate loader to handle this file type.
TypeError: Cannot read property 'ecmaFeatures' of undefined
    at Parser.parseTopLevel (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/espree/espree.js:271:18)
    at Parser.parse (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/acorn/dist/acorn.js:1636:17)
    at Object.parse (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/acorn/dist/acorn.js:905:44)
    at Parser.parse (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/webpack/lib/Parser.js:960:18)
    at Module.<anonymous> (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/webpack/lib/NormalModule.js:192:16)
    at /Users/davidfox-powell/dev/frontend-boilerplate/node_modules/webpack/lib/NormalModule.js:160:10
    at /Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:334:3
    at iterateNormalLoaders (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:182:10)
    at iterateNormalLoaders (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:189:10)
    at /Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:204:3
    at Object.context.callback (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:87:13)
    at Object.module.exports (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/babel-loader/index.js:89:8)
    at LOADER_EXECUTION (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
    at iterateNormalLoaders (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:189:10)
    at /Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:204:3
    at Object.context.callback (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:87:13)
    at Object.module.exports (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/eslint-loader/index.js:113:8)
    at LOADER_EXECUTION (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:95:14)
    at runSyncOrAsync (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:96:4)
    at iterateNormalLoaders (/Users/davidfox-powell/dev/frontend-boilerplate/node_modules/loader-runner/lib/LoaderRunner.js:200:2)
 @ multi main
```

**Comment by monteirocode** [comment] 2016-02-13 12:11
+1 getting error too
```
eslint-loader@1.2.1 requires a peer of eslint@^1.6.0 but none was installed.
```

**Comment by monteirocode** [comment] 2016-02-13 12:28
+1 getting errors too.

@dtothefp not sure what might be the cause of upgrading to `webpack 2` as I haven't tried it but I know the cause to upgrading to `eslint 2`.
```
eslint-loader@1.2.1 requires a peer of eslint@^1.6.0 but none was installed.
```
It's tied to a `peerDependencies` of `eslint 1.x` if you have eslint 2.0 installed it ignores it completely

```json
  "peerDependencies": {
    "eslint": "^1.6.0"
  }
```

A quick hack is to change the line to  `"eslint": "^2.0.0"` or `"eslint": "*"` 

Once the developers check if the package is compatible with `eslint 2.0` their should fix this error.

**Comment by dtothefp** [comment] 2016-02-13 15:01
@monteirocode I use npm 3 so peerDeendency is no longer an error, just warning. Looks like there is already and issue for that https://github.com/MoOx/eslint-loader/issues/79. 

It's impossible to use Webpck 2 without npm 3 because every loader has a peerDep on webpack 1.x

**Comment by dtothefp** [comment] 2016-02-13 17:25
If I were to guess I would say that something in espree/acorn is somehow conflicting. 

Webpack 2 has a dependency on `"acorn": "^2.4.0"`, and Eslint 2 has a dependency on `"espree": "^3.0.0"` which in turn has a dependency on `"acorn": "^2.7.0"`.

Eslint 2 has a dependency on `"espree": "^2.2.4"` which in turn has NO `acorn` dependency so I'm guessing whatever is happening is some sort of conflict in `acorn` but I'm unsure how this plays out.

I'm going to put on issue on Webpack 2 in hopes that @sokra has some ideas.

**Comment by MoOx** [comment] 2016-02-17 06:26
This package is totally compatible with eslint@2 as of 1.3.0 (which has just been released).
Not sure what is the problem here since I didn't tried webpack 2 yet.

**Comment by MoOx** [comment] 2016-02-17 06:27
And fyi, this loader don't have webpack as a peerdep.

**Comment by MoOx** [comment] 2016-07-28 06:06
Closing as it's working for a while for me.

**Closed by MoOx** 2016-07-28 06:06 UTC
